error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/vscode/vscode-server/bin/linux-x64/863d2581ecda6849923a2118d93a088b0745d9d6/bin/remote-cli:/home/pyo3/.local/bin:/home/pyo3/bin:/opt/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustc7hOIQZ/symbols.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.160eq5noxvc27mym.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.166tpv2sc5yaj539.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.1ajigcefj112ntm0.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.1esrigot90k1csks.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.1qdcdhn8u8uq2gyy.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.20z19r0e5o9ladvh.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.2473ldlw3fzssfp7.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.2yyxu0zplvxwbb72.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.3a89r60eg7vx1mmz.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.3eq3nz3ka1redcu5.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.407q4sd9q3g4hv5h.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.41414u50ugddzkky.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.42zqtxhvvagg92qo.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.46eozad36beidh1f.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.4kywd9duxr9is39o.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.4wvr6wzke83jzca8.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.55c2gninbk4mzn6p.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.57tld8pvwibrfqq2.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.58kfmzmnyhoflqrc.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.cuc2re128a3rvcd.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.etfmk21gwlled32.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.ldt9ep1xjf3kc05.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.sjp2il1oh5bbboe.rcgu.o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.3cnuig1g80a8safa.rcgu.o" "-Wl,--as-needed" "-L" "/workspaces/pyo3/target/debug/deps" "-L" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-d788bc66de795f45.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-6c3665e746796988.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-1aa39260c43636ed.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-852a4c7021558fa9.rlib" "/workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib" "/workspaces/pyo3/target/debug/deps/libmemoffset-aecaff760044dfb5.rlib" "/workspaces/pyo3/target/debug/deps/libportable_atomic-8c4a23bc98e6c36a.rlib" "/workspaces/pyo3/target/debug/deps/libparking_lot-511a2bcc00a39ecc.rlib" "/workspaces/pyo3/target/debug/deps/libparking_lot_core-6f8fead9cfce0b61.rlib" "/workspaces/pyo3/target/debug/deps/libcfg_if-a9f0e8a7b3b5c4c6.rlib" "/workspaces/pyo3/target/debug/deps/libsmallvec-05498bdf15f21cfb.rlib" "/workspaces/pyo3/target/debug/deps/liblock_api-49ef89c26b0ca176.rlib" "/workspaces/pyo3/target/debug/deps/libscopeguard-d492928046d34df8.rlib" "/workspaces/pyo3/target/debug/deps/libpyo3_ffi-30c9450d5a0659f0.rlib" "/workspaces/pyo3/target/debug/deps/liblibc-ff74f7bd64a06fab.rlib" "/workspaces/pyo3/target/debug/deps/libunindent-ec10873523e1e55b.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6e3078511c661ac3.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-252c22ad03c975c9.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-d80cad399a4d0390.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-27491650d14ec48b.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-97d68acfa4555965.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c70b304f6ac84900.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-d55f2ec1b1801f29.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-0b96f850bca44a32.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-ee200428a02d516d.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-53d84a0642c19f2b.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-217c01f7aaf0f8d4.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-2b97858586af9abb.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-cc333506f95be41d.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-690e7438295ce0c8.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-c9c6c96eccfdab53.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-cb895a9d9d73a7fa.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-433bd1aab5f6d647.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-5f8e0208f8278cbc.rlib" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-1088ecd7666b60f4.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/opt/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/bin/ld: /workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.407q4sd9q3g4hv5h.rcgu.o: in function `pyo3::conversions::std::num::<impl pyo3::conversion::ToPyObject for u64>::to_object':
          /workspaces/pyo3/src/conversions/std/num.rs:84: undefined reference to `PyLong_FromUnsignedLongLong'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/test_dict_iter-ca39397b4ffe76c6.etfmk21gwlled32.rcgu.o: in function `<pyo3::types::dict::BoundDictIterator as core::iter::traits::iterator::Iterator>::next':
          /workspaces/pyo3/src/types/dict.rs:631: undefined reference to `PyDict_Next'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.24cn58edy3daohhv.rcgu.o): in function `<pyo3::gil::GILGuard as core::ops::drop::Drop>::drop':
          /workspaces/pyo3/src/gil.rs:241: undefined reference to `PyGILState_Release'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.24cn58edy3daohhv.rcgu.o): in function `pyo3_ffi::object::Py_DECREF':
          /workspaces/pyo3/pyo3-ffi/src/object.rs:624: undefined reference to `_Py_Dealloc'
          /usr/bin/ld: /workspaces/pyo3/pyo3-ffi/src/object.rs:624: undefined reference to `_Py_Dealloc'
          /usr/bin/ld: /workspaces/pyo3/pyo3-ffi/src/object.rs:624: undefined reference to `_Py_Dealloc'
          /usr/bin/ld: /workspaces/pyo3/pyo3-ffi/src/object.rs:624: undefined reference to `_Py_Dealloc'
          /usr/bin/ld: /workspaces/pyo3/pyo3-ffi/src/object.rs:624: undefined reference to `_Py_Dealloc'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.24cn58edy3daohhv.rcgu.o):/workspaces/pyo3/pyo3-ffi/src/object.rs:624: more undefined references to `_Py_Dealloc' follow
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.3c8rtcda5mkybp6n.rcgu.o): in function `pyo3::types::dict::PyDict::new_bound':
          /workspaces/pyo3/src/types/dict.rs:74: undefined reference to `PyDict_New'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.3c8rtcda5mkybp6n.rcgu.o): in function `<pyo3::instance::Bound<pyo3::types::dict::PyDict> as pyo3::types::dict::PyDictMethods>::set_item::inner':
          /workspaces/pyo3/src/types/dict.rs:459: undefined reference to `PyDict_SetItem'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.3k29ydjgso5kbq2a.rcgu.o): in function `pyo3::err::PyErr::print_panic_and_unwind':
          /workspaces/pyo3/src/err/mod.rs:480: undefined reference to `PyErr_PrintEx'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.3k29ydjgso5kbq2a.rcgu.o): in function `pyo3::err::PyErr::new_type_bound':
          /workspaces/pyo3/src/err/mod.rs:577: undefined reference to `PyErr_NewExceptionWithDoc'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.3k29ydjgso5kbq2a.rcgu.o): in function `pyo3::err::PyErr::write_unraisable_bound':
          /workspaces/pyo3/src/err/mod.rs:721: undefined reference to `PyErr_WriteUnraisable'
          /usr/bin/ld: /workspaces/pyo3/target/debug/deps/libpyo3-c24dc0fbf0c99ee2.rlib(pyo3-c24dc0fbf0c99ee2.3k29ydjgso5kbq2a.rcgu.o): in function `pyo3::err::panic_after_error':


...


ak8ospgirnbjrb.rcgu.o): in function `pyo3::types::iterator::PyIterator::from_bound_object':
          /workspaces/pyo3/src/types/iterator.rs:52: undefined reference to `PyObject_GetIter'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)

error: could not compile `pyo3` (test "test_proto_methods") due to 1 previous error